# Generated by Django 4.1.2 on 2022-12-12 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlift', models.CharField(default=' ', max_length=300)),
                ('squat', models.CharField(default=' ', max_length=300)),
                ('bench', models.CharField(default=' ', max_length=300)),
                ('clean', models.CharField(default=' ', max_length=300)),
                ('snatch', models.CharField(default=' ', max_length=300)),
                ('ohp', models.CharField(default=' ', max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
