# Generated by Django 4.1.1 on 2022-11-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_workoutentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutentry',
            name='user',
        ),
    ]
